### PR TITLE
feat: Add instrumented tests to test UI

### PR DESCRIPTION
**Pull request by AKushch1337**
- Very long process but totaly worth it (COPIUM)

### CODE REVIEW

**Comment by AKushch1337** [comment]
The checks work fine, I just decided to cancel them manually, because of how long they take, as there is no sense for them in this branch

**Review by neliudochka — APPROVED** [review]
image

**Comment by neliudochka** [comment]
okay, you can continue cerebral you now what

**Comment by AKushch1337** [comment]
> okay, you can continue cerebral you now what

as a matter of fact, unfortunately I know what you mean!

**Pull request merged**
